### ISSUE TITLE
Case sensitive paths

### ISSUE THREAD

**Issue by jahewson** [at-icons/material#6]
Webpack's [CaseSensitivePathsPlugin](https://github.com/Urthen/case-sensitive-paths-webpack-plugin) detects the following case-sensitive path inconsistencies in the `index.js` file for `v0.4.0`:

`RaspberryPiIcon.js` -> `RaspberrypiIcon.js`
`StackExchangeIcon.js` -> `StackexchangeIcon.js`
`VisualStudioIcon.js` -> `VisualstudioIcon.js`

Renaming the above files will fix it.

**Comment by casesandberg** [comment]
Thanks! This has been fixed in `@icons/material@0.4.1`!

**Comment by jahewson** [comment]
Speedy! Thank you.
