### ISSUE TITLE
Missing icon from set

### ISSUE THREAD

**Issue by rardoz** [at-icons/material#7]
I'm not able to find the contact phone icon:

https://material.io/tools/icons/?search=contact&icon=contact_phone&style=baseline

**Comment by casesandberg** [comment]
This package auto-generates icons based off of https://materialdesignicons.com/. If you would like to see this icon I would suggest opening up a ticket at https://github.com/Templarian/MaterialDesign for this project to be able to pull it in.

**Comment by rardoz** [comment]
I've opened up an issue.

https://github.com/Templarian/MaterialDesign/issues/4118
