### ISSUE TITLE
What license is this project under?

### ISSUE THREAD

**Issue by nwestbury** [at-icons/material#8]
I'm evaluating whether to use [react-color](https://github.com/casesandberg/react-color) at work and we require to have permissive licenses.

Is this licensed under MIT? It seems like [npm](https://www.npmjs.com/package/@icons/material) says so but there is no LICENSE file. If it's the case, could I kindly ask that a LICENSE file be included in a similar format to the [react-color](https://github.com/casesandberg/react-color/blob/master/LICENSE).

Happy to make a PR if that'd make it easier but it's basically just copy-pasting that file at the root of the project.

Thanks for your awesome work on open source! Sorry to bug you with such a bureaucratic issue :)

**Comment by casesandberg** [comment]
The package is [specified and licensed as MIT](https://github.com/at-icons/material/blob/master/package.json#L14)! If your company needs a license file specifically I can add one.

**Comment by nwestbury** [comment]
Great! Yeah, if you'd be willing to add a `LICENSE` file at the root similar to what you've already done in your `react-color` project, this will make our legal team happy and clear the way for us to use this package, we have a requirement that the license be somewhere in the source tree. Thanks!

**Comment by nwestbury** [comment]
I've made a [PR](https://github.com/at-icons/material/pull/9) but feel free to commit directly if that's easier or if you want to stay as the only author.

**Comment by nwestbury** [comment]
Resolved. Thanks again.
